In [ ]:
%load_ext autoreload
%autoreload 2
%matplotlib widget
%pdb off

from pyCascade import utils
from pyCascade.probeReadWrite import read_probes_file_switch
from filloutVentilationStats import *
import flowEmulationUtils as feUtils
from matplotlib import pyplot as plt
from matplotlib import cm, colors
import matplotlib.ticker as ticker
import matplotlib.colors as mcolors
import numpy as np
import scipy as sp
import os
from IPython.core.debugger import set_trace
import pandas as pd
import seaborn as sns
from cycler import cycler
import plotly.express as px
import plotly
import plotly.graph_objects as go
from plotly.offline import plot
from plotly.subplots import make_subplots
from IPython.display import display, HTML
import statsmodels.api as sm
import warnings
import ast
from scipy.optimize import minimize
import seaborn as sns
import pyafn
from pyafn.constants import g, beta, rho, Cd

plotly.offline.init_notebook_mode()
display(HTML(
    '<script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_SVG"></script>'
))

plt.rcParams['figure.dpi'] = 140
im_scaling = .75
plt.rcParams['figure.figsize'] = [6.4 * im_scaling, 4.8 * im_scaling]

############ Universal ################
scratch_home = os.getenv('SCRATCH') #need to set SCRATCH (even if there is no real SCRATCH) to the location where results are written
scratch_dir = f'{scratch_home}/Cascade/city_block_cfd'
home_dir = !pwd
home_dir = home_dir[0]

display(scratch_dir)
display(home_dir)
plt.close('all')

# Setup

## Runs

In [ ]:
multiRun_dir = f"{home_dir}/CHARLES/multiRuns/"
plotFolder = f"{multiRun_dir}"

## Read in results

In [ ]:
def evalStringAsList(s):
    if isinstance(s, str) and s[0] == "[" and s[-1] == "]":
        return ast.literal_eval(s)
    else:
        return s

In [ ]:
flowStatsMI = pd.read_csv(f"{multiRun_dir}/flowStatsMI.csv", index_col = [0,1])
roomVentilationMI = pd.read_csv(f"{multiRun_dir}/roomVentilationMI.csv", index_col = [0,1])


In [ ]:
# runSubset = []
# runSubset += [
#     2530, 2531, 2532, 
#     2540, 2541, 2542, 
#     2550, 2551, 2552, 
#     2560, 2561, 2562, 
#     3210, 3211, 3212, 
#     3220, 3221, 3222, 
#     3230, 3231, 3232, 
#     3240, 3241, 3242, 
# ]

# runSubset += [
#     2460, 2461, 2462, 
#     2470, 2471, 2472, 
#     2480, 2481, 2482, 
#     2490, 2491, 2492, 
#     3160, 3161, 3162, 
#     3170, 3171, 3172, 
#     3180, 3181, 3182, 
#     3190, 3191, 3192, 
# ]

# flowStatsMI = flowStatsMI.loc[runSubset]
# roomVentilationMI = roomVentilationMI.loc[runSubset]

In [ ]:
flowStatsMI = combine_stats(flowStatsMI, ["WS", "delT", "SS", "C", "A", "slAll"], index_col = "csId")
roomVentilationMI = combine_stats(roomVentilationMI,   ["WS", "delT", "SS", "C", "A", "slAll"], index_col = "csId")

flowStatsMI = flowStatsMI[flowStatsMI["SS"] == True]
roomVentilationMI = roomVentilationMI[roomVentilationMI["SS"] == True]

flowStatsMI = replace_sl_with_h_df(flowStatsMI)
roomVentilationMI = replace_sl_with_h_df(roomVentilationMI)

flowStatsMI.loc[flowStatsMI["houseType"] == "-1-0", "slAll"] = True
roomVentilationMI.loc[roomVentilationMI["houseType"] == "-1-0", "slAll"] = True

flowStatsMI.loc[flowStatsMI["openingType"] == "skylight", "y"] += hm / 8

In [ ]:
flowStatsMI.loc[flowStatsMI["openingType"] == "skylight", "y"]

In [ ]:
# 2*flowStatsMI2.loc[2495]["rms-sn_prod(abs(u))-Norm"]**2 - flowStatsMI.loc[2460]["rms-sn_prod(abs(u))-Norm"]**2 - flowStatsMI.loc[2530]["rms-sn_prod(abs(u))-Norm"]**2

In [ ]:
runsNoInt = {
    257: {'A': 45, 'WS': 2, 'C': 2},
    258: {'A': 45, 'WS': 4, 'C': 2},
    259: {'A': 0,  'WS': 2, 'C': 2},
    260: {'A': 0,  'WS': 4, 'C': 2},

    325: {'A': 45, 'WS': 2, 'C': 3},
    326: {'A': 45, 'WS': 4, 'C': 3},
    327: {'A': 0,  'WS': 2, 'C': 3},
    328: {'A': 0,  'WS': 4, 'C': 3},
}

In [ ]:
pcOverwrite = False

def getNoIntRun(df, A, WS, C):
    filtered = df[(df['A'] == A) & (df['WS'] == WS) & (df['C'] == C)]
    if not filtered.empty:
        return filtered.index[0]
    return None

if pcOverwrite or os.path.exists(f"{multiRun_dir}/pointCloudStatsNoIntMI.csv") == False:
    # pointCloud pressure probes
    runIndex = flowStatsMI.index.get_level_values(0).unique()
    runIndex = np.sort(runIndex)
    pcStats = pd.DataFrame()

    def addB(name):
        if name.split("_")[-1][0] != "B":
            return f"{name}_B"
        return name

    for run in runIndex:
        A = flowStatsMI.loc[run, "A"].iloc[0]
        WS = flowStatsMI.loc[run, "WS"].iloc[0]
        C = flowStatsMI.loc[run, "C"].iloc[0]
        R = getNoIntRun(pd.DataFrame(runsNoInt).T, A, WS, C)
        V = run % 10
        if V == 0:
            stats = pd.read_csv(f"{home_dir}/CHARLES/config{C}/R{R%100}/probes/flowStats-40000to119000.csv", index_col = 0)
            stats.index = stats.index.map(addB)
            stats.columns = [str(col).replace('-119000', '') for col in stats.columns]
            stats.columns = [col + "-noInt" for col in stats.columns]
        stats["run"] = run
        stats["run-noInt"] = R * 10 + V
        stats = replace_sl_with_h_df(stats, level=0)
        pcStats = pd.concat([pcStats, stats], axis = "rows")

    pcStatsMI = pcStats.reset_index()
    pcStatsMI = pcStatsMI.set_index(['run', 'index'])
    pcStatsMI.to_csv(f"{multiRun_dir}/pointCloudStatsNoIntMI.csv")
else:
    pcStatsMI = pd.read_csv(f"{multiRun_dir}/pointCloudStatsNoIntMI.csv", index_col=[0,1])

In [ ]:
# Check that the window identifiers are the same

def check_equivalence(s1, s2, tol = 2e-1):
    s1.dropna(inplace=True)
    s2.dropna(inplace=True)
    if s1.dtype == float and s2.dtype == float:
        return (abs(s1 - s2) < tol)
    return s1 == s2

match_cols = ["x", "z", "orientation"]
match_cols = [f"{col}-noInt" for col in match_cols]
flowStatsMI[pcStatsMI.columns] = np.nan
flowStatsMI.update(pcStatsMI)

for col in flowStatsMI.columns:
    if "noInt" in col and flowStatsMI[col].dtype != float:
        match_cols.append(col)

for match_col in match_cols:
    ref_col = match_col.removesuffix("-noInt")
    s_match = check_equivalence(flowStatsMI[ref_col], flowStatsMI[match_col])
    if s_match.all():
        flowStatsMI.drop(match_col, inplace=True, axis="columns")
    else:
        display(flowStatsMI.loc[s_match == False, :])
        raise ValueError(f"Mismatch in {ref_col} and {match_col}")
            
# flowStatsMI

In [ ]:
# Extract velocity components as separate variables
u = flowStatsMI["comp(u_avg,0)-noInt"].values  # x-component
v = flowStatsMI["comp(u_avg,2)-noInt"].values  # y-component
w = flowStatsMI["comp(u_avg,1)-noInt"].values  # z-component

# Calculate magnitude
velocity_magnitude = np.sqrt(u**2 + v**2 + w**2)

# Calculate spherical angles
azimuth = np.degrees(np.arctan2(v, u))  # Angle in xy-plane
elevation = np.degrees(np.arccos(w/velocity_magnitude))  # Angle from z-axis

# Now use these variables for visualization
fig = px.scatter(x=u, y=v, color=flowStatsMI["openingType"], 
                 labels={"x": "u component", "y": "w component"}, 
                 title="Velocity Components")
fig.show()

# Create a scatter plot showing the angular distribution
fig2 = px.scatter(x=azimuth, y=elevation, color=flowStatsMI["openingType"],
                  size=velocity_magnitude,
                  labels={"x": "Azimuth Angle (°)", "y": "Elevation Angle (°)"},
                  title="Velocity Vector Orientation")
fig2.show()

In [ ]:
# +------------------------------------------------------------------------+
# |                     Mixture-of-Six-Planes via RANSAC                    |
# +------------------------------------------------------------------------+

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

def fit_plane_ransac(V_norm, epsilon=1e-3, num_iters=1000):
    """
    RANSAC-fit a plane through the origin to normalized vectors.
    Returns best‐fit unit normal and inlier mask.
    """
    best_n = None
    best_inliers = None
    best_count = 0
    N = V_norm.shape[0]
    
    for _ in range(num_iters):
        # pick two distinct vectors at random
        i, j = np.random.choice(N, 2, replace=False)
        vi, vj = V_norm[i], V_norm[j]
        
        # candidate normal
        n = np.cross(vi, vj)
        norm_n = np.linalg.norm(n)
        if norm_n < 1e-6:
            continue
        n /= norm_n
        
        # make hemisphere choice deterministic
        if n[np.argmax(np.abs(n))] < 0:
            n = -n
        
        # count inliers
        dots = np.abs(V_norm @ n)
        inliers = dots < epsilon
        count = inliers.sum()
        
        if count > best_count:
            best_count = count
            best_n = n
            best_inliers = inliers
    
    return best_n, best_inliers

def find_planes(u, v, w, n_planes=6, epsilon=1e-3, num_iters=1000):
    """
    Sequentially RANSAC-fit up to six planes to (u,v,w) velocity data.
    Returns:
      normals      : K×3 array of plane normals (K ≤ 6)
      assignments  : length-N array of plane indices [0…K-1] or -1 for outliers
    """
    # stack and normalize
    V = np.stack((u, v, w), axis=1)
    norms = np.linalg.norm(V, axis=1, keepdims=True)
    V_norm = np.zeros_like(V)
    nonzero = norms[:,0] > 0
    V_norm[nonzero] = V[nonzero] / norms[nonzero]
    
    N = V_norm.shape[0]
    assignments = np.full(N, -1, dtype=int)
    normals = []
    available = np.ones(N, dtype=bool)
    
    for k in range(n_planes):
        idxs = np.where(available)[0]
        if idxs.size < 2:
            break
        
        sub_V = V_norm[available]
        n, inliers_sub = fit_plane_ransac(sub_V, epsilon, num_iters)
        if n is None:
            break
        
        normals.append(n)
        
        # map back to full mask
        in_full = np.zeros(N, dtype=bool)
        in_full[idxs[inliers_sub]] = True
        
        assignments[in_full] = k
        available[in_full] = False
    
    return np.array(normals), assignments

def plot_planes_and_vectors(normals, u, v, w, assignments):
    """
    Plot the velocity directions colored by assigned plane and fitted plane normals on a unit sphere.

    Parameters
    ----------
    normals : array_like, shape (K,3)
        Unit normals of fitted planes.
    u, v, w : array_like, shape (N,)
        Velocity components.
    assignments : array_like, shape (N,)
        Plane indices [0..K-1] for each vector, or -1 for outliers.
    """
    import numpy as np
    import matplotlib.pyplot as plt

    # Stack & normalize velocities
    V = np.stack((u, v, w), axis=1)
    norms_V = np.linalg.norm(V, axis=1, keepdims=True)
    V_norm = np.zeros_like(V)
    nz = norms_V[:, 0] > 0
    V_norm[nz] = V[nz] / norms_V[nz]

    # Normalize plane normals
    normals_norm = normals / np.linalg.norm(normals, axis=1, keepdims=True)
    K = normals_norm.shape[0]

    # Create unit-sphere mesh
    phi = np.linspace(0, np.pi, 40)
    theta = np.linspace(0, 2 * np.pi, 40)
    phi, theta = np.meshgrid(phi, theta)
    X = np.sin(phi) * np.cos(theta)
    Y = np.sin(phi) * np.sin(theta)
    Z = np.cos(phi)

    # Prepare colormap
    cmap = plt.get_cmap('tab10', K)

    # Plot
    fig = plt.figure(figsize=(8, 8))
    ax = fig.add_subplot(111, projection='3d')
    ax.plot_wireframe(X, Y, Z, rstride=4, cstride=4, linewidth=0.5,
                     color='gray', alpha=0.5)

    # Scatter velocities by assignment
    for k in range(K):
        mask = (assignments == k)
        if np.any(mask):
            ax.scatter(
                V_norm[mask, 0], V_norm[mask, 1], V_norm[mask, 2],
                marker='o', s=5, color=cmap(k), label=f'velocities: plane {k}'
            )
    # Plot outliers if any
    out_mask = (assignments == -1)
    if np.any(out_mask):
        ax.scatter(
            V_norm[out_mask, 0], V_norm[out_mask, 1], V_norm[out_mask, 2],
            marker='x', s=30, color='k', label='outliers'
        )

    # Plot normals colored to match planes
    for k, n in enumerate(normals_norm):
        ax.scatter(
            n[0], n[1], n[2], marker='^', s=100,
            color=cmap(k), edgecolor='k', label=f'normal {k}'
        )

    ax.set_xlabel('X')
    ax.set_ylabel('Y')
    ax.set_zlabel('Z')
    ax.set_title('Velocity Directions and Plane Normals on Unit Sphere')
    ax.set_box_aspect([1, 1, 1])
    ax.legend(loc='upper right', bbox_to_anchor=(1.3, 1))
    plt.tight_layout()
    plt.show()

# === USAGE ===

# 1) Load or define your velocity components here:
#    (each must be a 1D NumPy array of the same length)
# u = np.array([...])
# v = np.array([...])
# w = np.array([...])

# For demo, we’ll simulate random data below—comment out in real use:
# np.random.seed(0)
# u, v, w = (np.random.randn(300), np.random.randn(300), np.random.randn(300))

# 2) Fit up to six planes:
epsilon = 1e-1       # tolerance for inliers: adjust to your noise level
num_iters = 2000     # RANSAC trials per plane
magnitude = np.sqrt(u**2 + v**2 + w**2)
mag_lim = 0.1
valid = magnitude > mag_lim
u_valid = u[valid]
v_valid = v[valid]
w_valid = w[valid]

print(f"Valid data points: {valid.sum()} out of {len(valid)} based on magnitude > {mag_lim}")
normals, assignments = find_planes(u_valid, v_valid, w_valid, 8, epsilon, num_iters)

print(f"Fitted {len(normals)} plane normals:")
print(normals)

n_per_plane = [(assignments==k).sum() for k in range(len(normals))]
print("Counts per plane:", n_per_plane)
print("Outliers:", (assignments==-1).sum())

# 3) Visualize:
plot_planes_and_vectors(normals, u_valid, v_valid, w_valid, assignments)

In [ ]:
# Compute azimuth and elevation in degrees
# Azimuth: angle in the XY plane from +X axis
# Elevation: angle from the XY plane up to the vector
azimuth   = np.degrees(np.arctan2(normals[:, 1], normals[:, 0]))
elevation = np.degrees(np.arcsin(normals[:, 2]))

# Plot
plt.figure(figsize=(6, 6))
plt.scatter(azimuth, elevation, marker='x', s=100)

# Annotate each point with its normal index
for i, (a, e) in enumerate(zip(azimuth, elevation)):
    plt.text(a, e, f'{i}', fontsize=12,
             ha='right', va='bottom')

plt.xlabel('Azimuth (°)')
plt.ylabel('Elevation (°)')
plt.title('Plane Normals: Azimuth vs Elevation')
plt.grid(True)
plt.tight_layout()
plt.show()

In [ ]:
px.scatter(data_frame=flowStatsMI, x="EP_p_avg-noInt", y='EP_p_avg', symbol = "houseType", color = "roomType")

In [ ]:
flux_param = "mean-mass_flux"
flowStatsMI["flux"] = flowStatsMI[flux_param] / rho 
roomVentilationMI["flux"] = roomVentilationMI[flux_param] / rho

In [ ]:
flowStatsMI.loc[flowStatsMI["openingType"] == "skylight", "AofA"] = 180
flowStatsMI["cosAofA"] = np.round(np.cos(flowStatsMI["AofA"] * np.pi / 180), 2)
flowStatsMI["sinAofA"] = np.round(np.sin(flowStatsMI["AofA"] * np.pi / 180), 2)

for (run, room), row in roomVentilationMI.iterrows():
    windowKeyCols = roomVentilationMI.columns[
            roomVentilationMI.columns.str.contains("windowKeys")
        ].tolist()
    windowKeys = row[windowKeyCols].dropna()
    sinAofAs = []
    cosAofAs = []
    for i, windowKey in enumerate(windowKeys):
        sinAofAs.append(flowStatsMI.loc[(run, windowKey), "sinAofA"])
        cosAofAs.append(flowStatsMI.loc[(run, windowKey), "cosAofA"])

    roomVentilationMI.loc[(run, room), "sinAofA"] = np.mean(sinAofAs)
    roomVentilationMI.loc[(run, room), "cosAofA"] = np.mean(cosAofAs)

In [ ]:

def getC_ds_AofA(aCorner, aCross, aDual, aSingle, aSinA, aCosA, AofA = 180, roomType="corner"):
    AofA *= np.pi / 180
    C_d = aSinA * np.sin(AofA) + aCosA * np.cos(AofA)
    if roomType == "corner":
        return C_d + aCorner
    if roomType == "cross":
        return C_d + aCross
    if roomType == "dual":
        return C_d + aDual
    if roomType == "single":
        return C_d + aSingle
    
def getC_ds_AofA2(aCorner, aCross, aSingle, aCornerSinA, aCrossSinA, AofA = 180, roomType="corner"):
    AofA *= np.pi / 180
    if roomType == "corner":
        return aCornerSinA * np.sin(AofA) + aCorner
    if roomType == "cross":
        return aCrossSinA * np.sin(AofA) + aCross
    if roomType == "dual":
        return aCornerSinA * np.sin(AofA) + aCorner
    if roomType == "single":
        return aSingle

def getC_ds_AofA3(aCorner, aCross, aDual, aSingle, aSinA, aCosA, sSin2a, aCos2A, AofA = 180, roomType="corner"):
    AofA *= np.pi / 180
    C_d = aSinA * np.sin(AofA) + aCosA * np.cos(AofA) + sSin2a * np.sin(2 * AofA) + aCos2A * np.cos(2 * AofA)
    if roomType == "corner":
        return C_d + aCorner
    if roomType == "cross":
        return C_d + aCross
    if roomType == "dual":
        return C_d + aDual
    if roomType == "single":
        return C_d + aSingle

def getC_ds_EP(aCorner, aCross, aDual, aSingle, aShear, aNormal, shear=0, normal=0, roomType="corner"):
    C_d = aShear * shear + aNormal * normal
    if roomType == "corner":
        return C_d + aCorner
    if roomType == "cross":
        return C_d + aCross
    if roomType == "dual":
        return C_d + aDual
    if roomType == "single":
        return C_d + aSingle

def getC_ds_All(aCorner, aCross, aDual, aSingle, aSinA, aCosA,  aShear, aNormal, aWS, AofA = 180, shear=0, normal=0, WS=0, roomType="corner"):
    AofA *= np.pi / 180
    C_d = aSinA * np.sin(AofA) + aCosA * np.cos(AofA) + aShear * shear + aNormal * normal + aWS * WS
    if roomType == "corner":
        return C_d + aCorner
    if roomType == "cross":
        return C_d + aCross
    if roomType == "dual":
        return C_d + aDual
    if roomType == "single":
        return C_d + aSingle

def getC_ds_opening(aX, aZ, aXSinA, aZSinA, aXCosA, aZCosA, AofA=0, openingType="xwindow"):
    AofA *= np.pi / 180
    if openingType == "xwindow":
        return aX + aXSinA * np.sin(AofA) + aXCosA * np.cos(AofA)
    if openingType == "zwindow":
        return aZ + aZSinA * np.sin(AofA) + aZCosA * np.cos(AofA)
    
def get_C_ds_sl(aW_pos, aW_neg, aSl_pos, aSL_neg, openingType="skylight", sign=1):
    if sign >= 1:
        aW = aW_pos
        aSl = aSl_pos
    else:
        aW = aW_neg
        aSl = aSL_neg
    if openingType == "skylight":
        return aSl
    else:
        return aW

def get_piecewise_params(aWindowIn, aWindowOut, aSkylightin, aSkylightOut, rmsWindowIn, rmsWindowOut, rmsSkylightIn, rmsSkylightOut, openingType="xwindow"):
    if openingType == "xwindow" or openingType == "zwindow":
        return [aWindowIn, aWindowOut], [rmsWindowIn, rmsWindowOut]
    if openingType == "skylight":
        return [aSkylightin, aSkylightOut], [rmsSkylightIn, rmsSkylightOut]


def getC_ds(row, params=None, typeC_d=None):
    AofA=row["AofA"]
    openingType=row["openingType"]
    roomType=row["roomType"]

    if typeC_d == "1":
        return 1
    if typeC_d == "AofA":
        return getC_ds_AofA(*params, AofA=AofA, roomType=roomType)
    if typeC_d == "AofA2":
        return getC_ds_AofA2(*params, AofA=AofA, roomType=roomType)
    if typeC_d == "AofA3":
        return getC_ds_AofA3(*params, AofA=AofA, roomType=roomType)
    if typeC_d == "piecewise":
        return get_piecewise_params(*params, openingType=openingType)
    
    shear=row["EP_shear"]
    normal=row["EP_normal"]
    
    if typeC_d == "EP":
        return getC_ds_EP(*params, shear=shear, normal=normal, roomType=roomType)
    if typeC_d == "All":
        return getC_ds_All(*params, AofA=AofA, shear=shear, normal=normal, WS=1, roomType=roomType)
    if typeC_d == "opening":
        return getC_ds_opening(*params, openingType=openingType)
    
    sign = np.sign(row["p-noInt_optp0-q_model"])
    if typeC_d == "skylight":
        return get_C_ds_sl(*params, openingType=openingType,  sign=sign)


def calculate_Cd(row):
    return getC_ds(
        row, 
        params=[Cd, Cd, Cd, Cd, 0, 0], #[0.5787617 , 0.64577319, 0.53346763, 0.64310922]
        typeC_d="AofA"
    )
flowStatsMI["C_d"] = flowStatsMI.apply(calculate_Cd, axis=1)

In [ ]:
# [1.16, 1.31, 1.15, 1, 0, 0]
flowStatsMI, roomVentilationMI = feUtils.update_flow_and_ventilation(flowStatsMI, roomVentilationMI, useDoors=True, tempStack=True,
    pTypes = {
        "pW": "mean-sn_prod(p)",
        "pEP": "EP_p_avg",
        "pEP-noInt": "EP_p_avg-noInt",
        "p-noInt": "p_avg-noInt"
    }
)


In [ ]:
# Check optp0Cd
flowStatsMICheck = flowStatsMI.copy()
roomVentilationMICheck = roomVentilationMI.copy()
flowStatsMICheck["C_d"] = flowStatsMICheck["p-noInt_optp0Cd-C_d"]

flowStatsMICheck, roomVentilationMICheck = feUtils.update_flow_and_ventilation(flowStatsMICheck, roomVentilationMICheck, optTypes = ["optp0"], useDoors=True, tempStack=True)

plt.figure()
plt.scatter(
    flowStatsMICheck["flux"], 
    flowStatsMICheck["p-noInt_optp0-q_model"], 
    s=3
)


In [ ]:
# flowStatsMINoSL = flowStatsMI[flowStatsMI["AofA"] % 1 == 0].copy()
# roomVentilationMINoSL = roomVentilationMI[roomVentilationMI["sinAofA"].notna()].copy()

In [ ]:
pVar = "p-noInt_optp0-q_model"
dfFit = flowStatsMI.dropna(subset=[pVar])
# Reshape x into a 2D column vector
x = dfFit[pVar].values.reshape(-1, 1)  # Ensure it's 2D
y = dfFit["flux"].values  # Keep y as 1D

# Solve for the slope (forcing intercept = 0)
CfitWindow, _, _, _ = np.linalg.lstsq(x, y, rcond=None)
CfitWindow = CfitWindow[0]

# Print the fitted coefficient
print("Fitted Coefficient:", CfitWindow)

# Fit C for each room type separately
room_types = dfFit['roomType'].unique()
CfitRoomTypes = {}

for room_type in sorted(room_types):
    dfRoomType = dfFit[dfFit['roomType'] == room_type]
    x = dfRoomType[pVar].values.reshape(-1, 1)  # Ensure it's 2D
    y = dfRoomType["flux"].values  # Keep y as 1D

    # Solve for the slope (forcing intercept = 0)
    Cfit, _, _, _ = np.linalg.lstsq(x, y, rcond=None)
    CfitRoomTypes[room_type] = Cfit[0]

# Print the fitted coefficients for each room type
for room_type, Cfit in CfitRoomTypes.items():
    print(f"Fitted Coefficient for {room_type}: {Cfit}")
    flowStatsMI.loc[flowStatsMI["roomType"] == room_type, "p-noInt_optp0-C_d"] = Cfit



In [ ]:
# Create the scatter plot
plt.figure(figsize=(10, 6))
hue = "roomType"
style = "skylight"
plotdf = flowStatsMI.copy()
plotdf["skylight"] = plotdf["openingType"].map(lambda x: "skylight" if x == "skylight" else "window")

# plotdf = plotdf[plotdf["slAll"] == False]
# plotdf = plotdf[plotdf["houseType"] == "0-1"]  # Filter for corner house type
# plotdf = plotdf[plotdf["AofA"] == 315]  # Filter for corner house type
# plotdf = plotdf[plotdf["C"] == 2]  # Filter for corner house type

plotdf = plotdf.sort_values(by=[hue, style])
sns.scatterplot(data=plotdf, x=pVar, y="flux", hue=hue, style=style, palette="colorblind")

# Overlay the lines from the fitted C values
x_vals = np.linspace(flowStatsMI["flux"].min(), flowStatsMI["flux"].max(), 100)

# plot 1:1 line as red dashed line
min_flux = flowStatsMI["flux"].min()
max_flux = flowStatsMI["flux"].max()
plt.plot([min_flux, max_flux], [min_flux, max_flux], color='red', linestyle='--', label='1:1 Line')

# Overall fitted line
y_vals_overall = x_vals * CfitWindow
plt.plot(x_vals, y_vals_overall, label='Overall Fit', color='black', linestyle=':')

plt.xlabel("Modeled Flux Velocity [m/s]", fontsize=14)
plt.ylabel("LES Flux Velocity [m/s]", fontsize=14)
plt.legend(fontsize=14, loc='upper left', title=None)
# plt.legend([], [], frameon=False)

# # Fitted lines for each room type
# for room_type, Cfit in CfitRoomTypes.items():
#     y_vals_room = Cfit * x_vals
#     plt.plot(x_vals, y_vals_room, label=f'{room_type} Fit')

# plt.legend()
# plt.xlabel(pVar)
# plt.ylabel("Flux")
# plt.title('Scatter Plot with Fitted Lines')

In [ ]:
roomVentilationMI[roomVentilationMI["roomType"]=="corner"][pVar]

In [ ]:
# Create the scatter plot
hue = "roomType"

plt.figure(figsize=(10, 6))
sns.scatterplot(data=roomVentilationMI, x=pVar, y="flux", hue=hue, palette="colorblind")

plt.legend()
plt.xlabel(pVar)
plt.ylabel("Flux")
plt.title('Scatter Plot with Fitted Lines')
plt.legend([], [], frameon=False)

dfFit = roomVentilationMI.dropna(subset=[pVar])
# Reshape x into a 2D column vector
x = dfFit[pVar].values.reshape(-1, 1)  # Ensure it's 2D
y = dfFit["flux"].values  # Keep y as 1D

# Solve for the slope (forcing intercept = 0)
CfitRoom, _, _, _ = np.linalg.lstsq(x, y, rcond=None)
CfitRoom = CfitRoom[0]

# Plot the fitted line
x_vals = np.linspace(roomVentilationMI["flux"].min(), roomVentilationMI["flux"].max(), 100)
y_vals_room = x_vals * CfitRoom
plt.plot(x_vals, y_vals_room, label='Room Fit', color='black', linestyle=':')

# Overlay the 1:1 line
min_flux = roomVentilationMI["flux"].min()
max_flux = roomVentilationMI["flux"].max()
plt.plot([min_flux, max_flux], [min_flux, max_flux], color='red', linestyle='--', label='1:1 Line')

plt.xlabel("Modeled Flux Velocity [m/s]", fontsize=14)
plt.ylabel("LES Flux Velocity [m/s]", fontsize=14)
plt.legend()
plt.legend([], [], frameon=False)


In [ ]:
flowStatsMI["u_mag-noInt"] = np.sqrt(flowStatsMI["comp(u_avg,0)-noInt"]**2 + flowStatsMI["comp(u_avg,1)-noInt"]**2 + flowStatsMI["comp(u_avg,2)-noInt"]**2)
flowStatsMI.to_csv(f"{multiRun_dir}/flowStatsMIEmulation.csv")
roomVentilationMI.to_csv(f"{multiRun_dir}/roomVentilationMIEmulation.csv")

In [ ]:
"""
Angles:
array([ 1.17340176,  1.32334274,  1.15833887,  0.00804852, -0.03391678,
        0.01388756])
0.14092224654844634

Shear/Normal:
array([ 1.16847614e+00,  1.31839869e+00,  1.17020841e+00,  1.62123154e-04,
        1.76884283e-04, -4.20435224e-04])
0.14068568319124428

Openning:
array([ 1.17383905e+00,  1.25949764e+00,  1.04268126e-05,  3.76369301e-05,
       -4.24760102e-05,  1.37200509e-04])
0.14497885547335324

AofA2:
array([ 1.17132613e+00,  1.31910337e+00,  2.03823868e-04, -4.39502373e-04,
        2.03392091e-04])
0.14071399814356256
"""

In [ ]:
def qRMSE(df):
    diff = (df["p-noInt_optp0-q_model"] - df["flux"]) / df["WS"]
    return np.sqrt(np.mean(diff**2))

def objective(params, flowStatsMI = flowStatsMI, roomVentilationMI = roomVentilationMI):
    # flowStatsMI = flowStatsMI.copy()
    # roomVentilationMI = roomVentilationMI.copy()

    display(params)
    def calculate_Cd(row):
        return getC_ds(
            row, 
            params=params, 
            typeC_d="piecewise"
            # typeC_d="AofA3"
        )
    flowStatsMI["C_d"] = flowStatsMI.apply(lambda x: calculate_Cd(x)[0], axis=1 )
    flowStatsMI["pRMS"] = flowStatsMI.apply(lambda x: calculate_Cd(x)[1], axis=1)
    flowStatsMI, roomVentilationMI = feUtils.update_flow_and_ventilation(flowStatsMI, roomVentilationMI, useDoors=True, tempStack=True, doorCd = [Cd, Cd], checkAnalytical=False,
    pTypes = {
        "p-noInt": "p_avg-noInt"
    }
)

    # RMSE = qRMSE(roomVentilationMI)
    RMSE = qRMSE(flowStatsMI)
    display(RMSE)
    return RMSE

initial_guess = [Cd*1.15, Cd*1.12, Cd*0.97, Cd*1.21, 0.11, 0.09, 1e-8, 0.13]
# result = minimize(objective, initial_guess, method='Nelder-Mead')

In [ ]:
# result

    #    message: Optimization terminated successfully.
    #    success: True
    #     status: 0
    #        fun: 0.04593738164581283
    #          x: [ 6.121e-01  6.467e-01  5.840e-01  6.464e-01  1.271e-01
    #               1.010e-01  9.888e-09  1.309e-01]
    #        nit: 157
    #       nfev: 345
    # final_simplex:

# (array([[6.12073872e-01, 6.46696843e-01, 5.83993726e-01, 6.46408493e-01,
#          1.27128287e-01, 1.00978006e-01, 9.88805588e-09, 1.30877891e-01],
#         [6.12073516e-01, 6.46696703e-01, 5.83993966e-01, 6.46408595e-01,
#          1.27128257e-01, 1.00977956e-01, 9.88806457e-09, 1.30877868e-01],
#         [6.12073687e-01, 6.46696933e-01, 5.83993849e-01, 6.46408595e-01,
#          1.27128296e-01, 1.00977943e-01, 9.88806208e-09, 1.30877834e-01],
#         [6.12073222e-01, 6.46696204e-01, 5.83994265e-01, 6.46408468e-01,
#          1.27128284e-01, 1.00977932e-01, 9.88807094e-09, 1.30877827e-01],
#         [6.12073491e-01, 6.46696661e-01, 5.83993937e-01, 6.46408645e-01,
#          1.27128236e-01, 1.00977939e-01, 9.88806605e-09, 1.30877902e-01],
#         [6.12073760e-01, 6.46696554e-01, 5.83993840e-01, 6.46408880e-01,
#          1.27128187e-01, 1.00977934e-01, 9.88806452e-09, 1.30877940e-01],
#         [6.12073281e-01, 6.46696626e-01, 5.83993991e-01, 6.46408675e-01,
#          1.27128278e-01, 1.00977918e-01, 9.88806918e-09, 1.30877867e-01],
#         [6.12073518e-01, 6.46696731e-01, 5.83993714e-01, 6.46408965e-01,
#          1.27128221e-01, 1.00977941e-01, 9.88806483e-09, 1.30877951e-01],
#         [6.12073772e-01, 6.46696874e-01, 5.83993802e-01, 6.46408655e-01,
#          1.27128198e-01, 1.00977946e-01, 9.88806292e-09, 1.30877933e-01]]),
#  array([0.04593738, 0.0459374 , 0.04593743, 0.04593745, 0.04593746,
#         0.04593758, 0.04593759, 0.04593764, 0.04595733]))


In [ ]:
def objective(params, flowStatsMI = flowStatsMI, roomVentilationMI = roomVentilationMI):
    # flowStatsMI = flowStatsMI.copy()
    # roomVentilationMI = roomVentilationMI.copy()

    display(params)
    def calculate_Cd(row):
        return getC_ds(
            row, 
            params=params, 
            typeC_d="piecewise"
            # typeC_d="AofA3"
        )
    flowStatsMI["C_d"] = flowStatsMI.apply(lambda x: calculate_Cd(x)[0], axis=1 )
    flowStatsMI["qRMS"] = flowStatsMI.apply(lambda x: calculate_Cd(x)[1], axis=1)
    flowStatsMI, roomVentilationMI = feUtils.update_flow_and_ventilation(flowStatsMI, roomVentilationMI, useDoors=True, tempStack=True, doorCd = [Cd, Cd], checkAnalytical=False,
    pTypes = {
        "p-noInt": "p_avg-noInt"
    }
)

    # RMSE = qRMSE(roomVentilationMI)
    RMSE = qRMSE(flowStatsMI)
    display(RMSE)
    return RMSE

# initial_guess = [Cd*1.15, Cd*1.12, Cd*0.97, Cd*1.21, 0.11, 0.09, 1e-8, 0.13]
initial_guess = [Cd, Cd, Cd, Cd, 0.1, 0.1, 1e-8, 0.1]
result = minimize(objective, initial_guess, method='Nelder-Mead')

In [ ]:
# display(result)
# display(result.final_simplex)

# message: Optimization terminated successfully.
#        success: True
#         status: 0
#            fun: 0.04488906555963882
#              x: [ 6.695e-01  6.576e-01  5.279e-01  6.764e-01  3.188e-01
#                   1.014e-01 -8.626e-09  8.762e-02]
#            nit: 223
#           nfev: 368
#  final_simplex: (array([[ 6.695e-01,  6.576e-01, ..., -8.626e-09,
#                          8.762e-02],
#                        [ 6.695e-01,  6.576e-01, ..., -8.626e-09,
#                          8.761e-02],
#                        ...,
#                        [ 6.695e-01,  6.576e-01, ..., -8.630e-09,
#                          8.763e-02],
#                        [ 6.695e-01,  6.576e-01, ..., -8.628e-09,
#                          8.763e-02]]), array([ 4.489e-02,  4.489e-02,  4.489e-02,  4.489e-02,
#                         4.489e-02,  4.489e-02,  4.489e-02,  4.489e-02,
#                         4.489e-02]))(array([[ 6.69534126e-01,  6.57598251e-01,  5.27908424e-01,
#           6.76420060e-01,  3.18821499e-01,  1.01415544e-01,
#          -8.62639987e-09,  8.76228478e-02],
#         [ 6.69530504e-01,  6.57608396e-01,  5.27965554e-01,
#           6.76446918e-01,  3.18813089e-01,  1.01401225e-01,
#          -8.62594413e-09,  8.76080149e-02],
#         [ 6.69533255e-01,  6.57601833e-01,  5.27975078e-01,
#           6.76425400e-01,  3.18803723e-01,  1.01420819e-01,
#          -8.62659919e-09,  8.76292986e-02],
#         [ 6.69543014e-01,  6.57596961e-01,  5.27871437e-01,
#           6.76384056e-01,  3.18828457e-01,  1.01407495e-01,
#          -8.62423216e-09,  8.76079130e-02],
#         [ 6.69529365e-01,  6.57608891e-01,  5.27960917e-01,
#           6.76451232e-01,  3.18809949e-01,  1.01417527e-01,
#          -8.62709590e-09,  8.76226265e-02],
#         [ 6.69538888e-01,  6.57592305e-01,  5.27972020e-01,
#           6.76436843e-01,  3.18818703e-01,  1.01416386e-01,
#          -8.62740014e-09,  8.76208068e-02],
#         [ 6.69524754e-01,  6.57619775e-01,  5.27918079e-01,
#           6.76435059e-01,  3.18801248e-01,  1.01422813e-01,
#          -8.62506988e-09,  8.76207844e-02],
#         [ 6.69538151e-01,  6.57592300e-01,  5.27999439e-01,
#           6.76453065e-01,  3.18826047e-01,  1.01416284e-01,
#          -8.62965622e-09,  8.76304527e-02],
#         [ 6.69533115e-01,  6.57600787e-01,  5.27957683e-01,
#           6.76456780e-01,  3.18814982e-01,  1.01415712e-01,
#          -8.62802900e-09,  8.76260161e-02]]),
#  array([0.04488907, 0.04488911, 0.04488914, 0.04488916, 0.04488917,
#         0.04488918, 0.04488919, 0.04488924, 0.04488924]))

In [ ]:
# display(result)
# display(result.final_simplex)

#        message: Optimization terminated successfully.
#        success: True
#         status: 0
#            fun: 0.04481782786847362
#              x: [ 6.647e-01  6.558e-01  5.395e-01  6.928e-01  2.923e-01
#                   1.106e-01 -1.354e-08  1.775e-01]
#            nit: 243
#           nfev: 407
#  final_simplex: (array([[ 6.647e-01,  6.558e-01, ..., -1.354e-08,
#                          1.775e-01],
#                        [ 6.648e-01,  6.558e-01, ..., -1.354e-08,
#                          1.775e-01],
#                        ...,
#                        [ 6.648e-01,  6.558e-01, ..., -1.355e-08,
#                          1.775e-01],
#                        [ 6.648e-01,  6.558e-01, ..., -1.354e-08,
#                          1.775e-01]]), array([ 4.482e-02,  4.482e-02,  4.482e-02,  4.482e-02,
#                         4.482e-02,  4.482e-02,  4.482e-02,  4.482e-02,
#                         4.482e-02]))
# 
# (array([[ 6.64745262e-01,  6.55790364e-01,  5.39491525e-01,
#           6.92849294e-01,  2.92316211e-01,  1.10592773e-01,
#          -1.35379981e-08,  1.77468215e-01],
#         [ 6.64774594e-01,  6.55776393e-01,  5.39520809e-01,
#           6.92835040e-01,  2.92351251e-01,  1.10596555e-01,
#          -1.35426284e-08,  1.77470812e-01],
#         [ 6.64759244e-01,  6.55779962e-01,  5.39527960e-01,
#           6.92855887e-01,  2.92369418e-01,  1.10602646e-01,
#          -1.35450962e-08,  1.77466792e-01],
#         [ 6.64796464e-01,  6.55773652e-01,  5.39586264e-01,
#           6.92856809e-01,  2.92385023e-01,  1.10595303e-01,
#          -1.35469001e-08,  1.77452028e-01],
#         [ 6.64769432e-01,  6.55764130e-01,  5.39483801e-01,
#           6.92868490e-01,  2.92371212e-01,  1.10601301e-01,
#          -1.35457866e-08,  1.77485310e-01],
#         [ 6.64767820e-01,  6.55788659e-01,  5.39494390e-01,
#           6.92856971e-01,  2.92361759e-01,  1.10597990e-01,
#          -1.35442093e-08,  1.77472129e-01],
#         [ 6.64759562e-01,  6.55787324e-01,  5.39487897e-01,
#           6.92865133e-01,  2.92372001e-01,  1.10601116e-01,
#          -1.35458176e-08,  1.77478987e-01],
#         [ 6.64758613e-01,  6.55804872e-01,  5.39464445e-01,
#           6.92858804e-01,  2.92371055e-01,  1.10601672e-01,
#          -1.35460277e-08,  1.77483017e-01],
#         [ 6.64751151e-01,  6.55756292e-01,  5.39536632e-01,
#           6.92857056e-01,  2.92331360e-01,  1.10594402e-01,
#          -1.35395436e-08,  1.77462325e-01]]),
#  array([0.04481783, 0.04481787, 0.04481791, 0.04481798, 0.04481805,
#         0.04481821, 0.04481841, 0.04481843, 0.04481848]))

In [ ]:
def objective(params, flowStatsMI = flowStatsMI, roomVentilationMI = roomVentilationMI):
    # flowStatsMI = flowStatsMI.copy()
    # roomVentilationMI = roomVentilationMI.copy()

    display(params)
    params = list(params) + [0, 0, 0, 0]
    def calculate_Cd(row):
        return getC_ds(
            row, 
            params=params, 
            typeC_d="piecewise"
            # typeC_d="AofA3"
        )
    flowStatsMI["C_d"] = flowStatsMI.apply(lambda x: calculate_Cd(x)[0], axis=1 )
    flowStatsMI["pRMS"] = flowStatsMI.apply(lambda x: [x["p_rms-noInt"], x["p_rms-noInt"]], axis=1)
    flowStatsMI, roomVentilationMI = feUtils.update_flow_and_ventilation(flowStatsMI, roomVentilationMI, useDoors=True, tempStack=True, doorCd = [Cd, Cd], checkAnalytical=False,
    pTypes = {
        "p-noInt": "p_avg-noInt"
    }
)

    # RMSE = qRMSE(roomVentilationMI)
    RMSE = qRMSE(flowStatsMI)
    display(RMSE)
    return RMSE

initial_guess = [6.121e-01, 6.467e-01, 5.840e-01, 6.464e-01]
# result = minimize(objective, initial_guess, method='Nelder-Mead')

In [ ]:
# result.final_simplex

# message: Optimization terminated successfully.
#        success: Truer
#         status: 0
#            fun: 0.038870778230361974
#              x: [ 6.882e-01  7.107e-01  6.848e-01  7.639e-01]
#            nit: 85
#           nfev: 166
#  final_simplex: (array([[ 6.882e-01,  7.107e-01,  6.848e-01,  7.639e-01],
#                        [ 6.882e-01,  7.107e-01,  6.847e-01,  7.639e-01],
#                        ...,
#                        [ 6.882e-01,  7.107e-01,  6.848e-01,  7.639e-01],
#                        [ 6.882e-01,  7.107e-01,  6.847e-01,  7.639e-01]]), array([ 3.887e-02,  3.887e-02,  3.887e-02,  3.887e-02,
#                         3.887e-02]))

# (array([[0.68820982, 0.71068943, 0.68477027, 0.76392744],
#         [0.68819325, 0.71070276, 0.68473584, 0.76393461],
#         [0.68820774, 0.71069658, 0.68475332, 0.76393889],
#         [0.68819408, 0.71068544, 0.68477366, 0.7639359 ],
#         [0.6881847 , 0.71069448, 0.68471618, 0.76394047]]),
#  array([0.03887078, 0.03887079, 0.03887079, 0.03887079, 0.03887272]))

In [ ]:
flowStatsMI.drop(columns=["pRMS"], inplace=True, errors="ignore")
def objective(params, flowStatsMI = flowStatsMI, roomVentilationMI = roomVentilationMI):
    # flowStatsMI = flowStatsMI.copy()
    # roomVentilationMI = roomVentilationMI.copy()

    display(params)
    params = list(params) + [0, 0, 0, 0]
    def calculate_Cd(row):
        return getC_ds(
            row, 
            params=params, 
            typeC_d="piecewise"
            # typeC_d="AofA3"
        )
    flowStatsMI["C_d"] = flowStatsMI.apply(lambda x: calculate_Cd(x)[0], axis=1 )
    flowStatsMI["qRMS"] = flowStatsMI.apply(lambda x: [x["rms-mass_flux"], x["rms-mass_flux"]], axis=1)
    flowStatsMI, roomVentilationMI = feUtils.update_flow_and_ventilation(flowStatsMI, roomVentilationMI, useDoors=True, tempStack=True, doorCd = [Cd, Cd], checkAnalytical=False,
    pTypes = {
        "p-noInt": "p_avg-noInt"
    }
)

    # RMSE = qRMSE(roomVentilationMI)
    RMSE = qRMSE(flowStatsMI)
    display(RMSE)
    return RMSE

initial_guess = [0.70551001, 0.72049902, 0.68320754, 0.71659452]
# result = minimize(objective, initial_guess, method='Nelder-Mead')

In [ ]:
# result.final_simplex
#        message: Optimization terminated successfully.
#        success: True
#         status: 0
#            fun: 0.0438323130445063
#              x: [ 7.022e-01  7.195e-01  6.934e-01  7.408e-01]
#            nit: 43
#           nfev: 102
#  final_simplex: (array([[ 7.022e-01,  7.195e-01,  6.934e-01,  7.408e-01],
#                        [ 7.022e-01,  7.195e-01,  6.933e-01,  7.408e-01],
#                        ...,
#                        [ 7.022e-01,  7.195e-01,  6.934e-01,  7.408e-01],
#                        [ 7.022e-01,  7.195e-01,  6.934e-01,  7.408e-01]]), array([ 4.383e-02,  4.383e-02,  4.383e-02,  4.383e-02,
#                         4.383e-02]))

# (array([[0.70223941, 0.71946309, 0.69335217, 0.74081058],
#         [0.70224733, 0.7194587 , 0.69334485, 0.74082287],
#         [0.70224654, 0.71945619, 0.69337159, 0.7408054 ],
#         [0.70224253, 0.71945919, 0.69340077, 0.74080155],
#         [0.70224213, 0.7194587 , 0.693378  , 0.74080605]]),
#  array([0.04383231, 0.04383235, 0.04383253, 0.04383272, 0.04383295]))

In [ ]:
plotdf = roomVentilationMI.copy()
plotdf["x"] = plotdf["mean-p-room"]**0.5
plotdf["y"] = plotdf["p-noInt_optp0Cd-p0"]**0.5
px.scatter(data_frame=plotdf, x="x", y='y', symbol = "roomType", color = "delT")

In [ ]:
px.box(data_frame=flowStatsMI.sort_values(["AofA", "roomType"]), x="p-noInt-C_d", color = "AofA", facet_col = "roomType")

In [ ]:
px.box(data_frame=flowStatsMI.sort_values(["AofA", "roomType"]), x="p-noInt_optp0Cd-C_d", color = "AofA", facet_col = "roomType")

In [ ]:
px.box(data_frame=flowStatsMI.sort_values(["AofA", "roomType"]), x="p-noInt_optp0Cd-C_d", facet_col = "openingType")

In [ ]:
from sklearn.cluster import KMeans
from sklearn.decomposition import TruncatedSVD

# Filter and sort the data
flowStatsMINoSL = flowStatsMI[flowStatsMI["AofA"] % 1 == 0]
flowStatsMINoSL.sort_values(by=["WS", "AofA"], inplace=True)

# Define substrings to keep and drop
subStrKeep = ["p-noInt-C_d", "sinAofA", "cosAofA", "roomType", "WS", "EP_normal", "EP_shear", "mean-mass_flux", "openingType"]
meanKmeansDf = flowStatsMINoSL[subStrKeep]

# Convert roomType to numeric
meanKmeansDf["roomType"] = meanKmeansDf["roomType"].astype('category').cat.codes
meanKmeansDf["openingType"] = meanKmeansDf["openingType"].astype('category').cat.codes

# Perform z-score normalization
mean = np.mean(meanKmeansDf, axis=0)
std = np.std(meanKmeansDf, axis=0)
meanKmeansDf = (meanKmeansDf - mean) / std

# Apply K-Means Algorithm
k = 4
kmeans = KMeans(n_clusters=k, random_state=0, n_init='auto')
kmeans.fit(meanKmeansDf)

# Assign cluster labels
flowStatsMINoSL["labels"] = kmeans.labels_.astype(str)

# Perform SVD decomposition
svd = TruncatedSVD(n_components=3)
meanKmeansDfLowDim = svd.fit_transform(meanKmeansDf)

# Visualize the clusters
fig = px.scatter_3d(data_frame=flowStatsMINoSL, x=meanKmeansDfLowDim[:, 0], y=meanKmeansDfLowDim[:, 1], z=meanKmeansDf["p-noInt-C_d"], color="labels")
fig.update_traces(marker=dict(size=3))
fig.update_layout(width=1200, height=800, legend=dict(x=0, y=1.1))
fig.show()

In [ ]:
# Perform SVD decomposition
svd = TruncatedSVD(n_components=meanKmeansDf.shape[1])
meanKmeansDfLowDim = svd.fit_transform(meanKmeansDf)

# Plot the magnitude of the eigenvalues
plt.figure()
plt.plot(range(1, len(svd.explained_variance_) + 1), svd.explained_variance_, marker='o')
plt.xlabel('Component Number')
plt.ylabel('Eigenvalue Magnitude')
plt.title('Magnitude of Eigenvalues')
plt.grid(True)
plt.show()

In [ ]:
corrDf = meanKmeansDf.copy()
corrDf['roomType'] = flowStatsMINoSL['roomType']

# Split the data by roomType
room_types = corrDf['roomType'].unique()

# Plot correlation matrices for each roomType
fig, axes = plt.subplots(2, 2, figsize=(10, 8))
axes = axes.flatten()

for ax, room_type in zip(axes, room_types):
    room_data = corrDf[corrDf['roomType'] == room_type]
    room_data = room_data.drop(columns='roomType')
    corr_matrix = room_data.corr()
    sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.1f', linewidths=0.5, ax=ax)
    ax.set_title(f'Correlation Matrix for Room Type {room_type}')

plt.tight_layout()

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Define the features (independent variables) and target (dependent variable)
features = ['AofA', 'roomType', 'WS', 'EP_normal', 'EP_shear', 'mean-mass_flux']
X = meanKmeansDf[features]
y = meanKmeansDf['p-noInt-C_d']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and fit the linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Squared Error: {mse}')
print(f'R^2 Score: {r2}')

# Display the coefficients
coefficients = pd.DataFrame(model.coef_, features, columns=['Coefficient'])
print(coefficients)

In [ ]:
px.scatter(data_frame=flowStatsMI, x="mean-mass_flux", y='p-noInt-q_model', color = "AofA_resid")

In [ ]:
import seaborn as sns

# Create the scatter plot
plt.figure(figsize=(10, 6))
sns.scatterplot(data=flowStatsMI, x="mean-mass_flux", y='pEP-q_model', hue="roomType", style="roomType")

# Overlay the lines from the fitted C values
x_vals = np.linspace(flowStatsMI["mean-mass_flux"].min(), flowStatsMI["mean-mass_flux"].max(), 100)

# Overall fitted line
y_vals_overall = CfitWindow * x_vals
plt.plot(x_vals, y_vals_overall, label='Overall Fit', color='black')

# Fitted lines for each room type
for room_type, Cfit in CfitRoomTypes.items():
    y_vals_room = Cfit * x_vals
    plt.plot(x_vals, y_vals_room, label=f'{room_type} Fit')

plt.legend()
plt.xlabel('Mean Mass Flux')
plt.ylabel('pEP-q_model')
plt.title('Scatter Plot with Fitted Lines')
plt.show()

In [ ]:
px.scatter(data_frame=roomVentilationMI, x="mean-mass_flux", y='p-noInt-q_model', symbol = "houseType", color = "roomType")

In [ ]:
px.scatter(data_frame=roomVentilationMI, x="mean-mass_flux", y='pEP-q_model', symbol = "houseType", color = "roomType")

In [ ]:
roomVentilationMI["sinAofA"]

In [ ]:
px.scatter(data_frame=roomVentilationMI, x="mean-mass_flux", y='pEP-q_model', symbol = "houseType", color = "sinAofA")

In [ ]:
dfFit = roomVentilationMI.dropna(subset=["p-noInt-q_model"])
# Reshape x into a 2D column vector
x = dfFit["mean-mass_flux"].values.reshape(-1, 1)  # Ensure it's 2D
y = dfFit["p-noInt-q_model"].values  # Keep y as 1D

# Solve for the slope (forcing intercept = 0)
CfitRooms, _, _, _ = np.linalg.lstsq(x, y, rcond=None)
CfitRooms = CfitRooms[0]

# Print the fitted coefficient
print("Fitted Coefficient:", CfitRooms)

In [ ]:
CfitRooms = 1
roomVentilationMI["q_model-diff"] = roomVentilationMI["p-noInt-q_model"]/CfitRooms - roomVentilationMI["mean-mass_flux"]
roomVentilationMI["q_model-error"] = roomVentilationMI["q_model-diff"] / roomVentilationMI["mean-mass_flux"]

fig, axs = plt.subplots(2, 2, constrained_layout=True, figsize=(8, 6))
conditions = [(2, 0), (2, 45), (3, 0), (3, 45)]
for ax, (C, A) in zip(axs.flat, conditions):
    plotdf = roomVentilationMI[(roomVentilationMI["C"] == C) & (roomVentilationMI["A"] == A)]
    im = ax.scatter(plotdf['x'], plotdf['z'], s=8*im_scaling, c=plotdf["q_model-error"], cmap='PiYG', edgecolors="black", linewidths=.1, vmin=-2, vmax=2)
fig.colorbar(im, ax=axs, orientation='vertical', fraction=0.02, pad=0.04)

fig, axs = plt.subplots(2, 2, constrained_layout=True, figsize=(8, 6))
for ax, (C, A) in zip(axs.flat, conditions):
    plotdf = roomVentilationMI[(roomVentilationMI["C"] == C) & (roomVentilationMI["A"] == A)]
    im = ax.scatter(plotdf['x'], plotdf['z'], s=8*im_scaling, c=plotdf["q_model-diff"], cmap='RdBu', edgecolors="black", linewidths=.1, vmin=-.25, vmax=.25)
fig.colorbar(im, ax=axs, orientation='vertical', fraction=0.02, pad=0.04)

In [ ]:
flowStatsMI["q_model-diff"] = flowStatsMI["p-noInt-q_model"]/CfitRooms - flowStatsMI["mean-mass_flux"]
flowStatsMI["q_model-error"] = flowStatsMI["q_model-diff"] / flowStatsMI["mean-mass_flux"]

fig, axs = plt.subplots(2, 2, constrained_layout=True, figsize=(8, 6))
conditions = [(2, 0), (2, 45), (3, 0), (3, 45)]
for ax, (C, A) in zip(axs.flat, conditions):
    plotdf = flowStatsMI[(flowStatsMI["C"] == C) & (flowStatsMI["A"] == A)]
    im = ax.scatter(plotdf['x'], plotdf['z'], s=8*im_scaling, c=plotdf["q_model-error"], cmap='PiYG', edgecolors="black", linewidths=.1, vmin=-2, vmax=2)
fig.colorbar(im, ax=axs, orientation='vertical', fraction=0.02, pad=0.04)

fig, axs = plt.subplots(2, 2, constrained_layout=True, figsize=(8, 6))
conditions = [(2, 0), (2, 45), (3, 0), (3, 45)]
for ax, (C, A) in zip(axs.flat, conditions):
    plotdf = flowStatsMI[(flowStatsMI["C"] == C) & (flowStatsMI["A"] == A)]
    im = ax.scatter(plotdf['x'], plotdf['z'], s=8*im_scaling, c=plotdf["q_model-diff"], cmap='RdBu', edgecolors="black", linewidths=.1, vmin=-.25, vmax=.25)
fig.colorbar(im, ax=axs, orientation='vertical', fraction=0.02, pad=0.04)